### PR TITLE
Fixed style.css

### PR DESCRIPTION
**Pull request by tmatsuo**
This file has ${symbol_pound} for pound sign and it is wrong since maven don't filter this file according to https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/hello-endpoints-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@lesv I will appreciate it if you can take a look.

**Comment by tmatsuo** [comment]
Sorry it's not ready yet. I'll ping you when it's ready.

**Comment by tmatsuo** [comment]
@lesv OK, it's ready. Please take a look.

FYI, you can test the archetype locally by the following:

```
$ mvn install  # this will install your archetype to your local maven repo
$ cd /somewhere/clean
$ mvn archetype:generate -DarchetypeCatalog=local
$ cd your-artifact-name
$ mvn appengine:devserver
```

**Comment by lesv** [comment]
In general ok, I'd rather separate the core info  appengine.version from app.version rather than appengine.app.version.

I test locally using a bit more complex mechanism, but similar.

**Comment by tmatsuo** [comment]
> I'd rather separate the core info appengine.version from app.version rather than appengine.app.version.

What do you mean? Can you elaborate?

**Comment by tmatsuo** [comment]
Alright, removed appengine.app.version. PTAL

**Comment by lesv** [comment]
LGTM

**Pull request merged**
