### PR TITLE
fix some warnings and grammar issues in generated code

### PR DESCRIPTION
**Pull request by elharo**
@lesv

### CODE REVIEW

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
Please resolve the conflicts before merging...

**Comment by elharo** [comment]
I think I've figured out how to merge across forks now. You'll still need to merge this since I don't have write access to this repo.

**Comment by lesv** [comment]
I'll try to test all this stuff and send to the repo by EoD tomorrow.  (if you don't see a comment please ping)

**Pull request merged**
