### PR TITLE
application tag no longer required

### PR DESCRIPTION
**Pull request by lesv**
1. Remove `<application>` tag from `appengine-web.xml`
2. Local JSP’s work w/ J8, so remove warning.
3. Bump the version for the archetype.

### CODE REVIEW

**Comment by lesv** [comment]
@GoogleCloudPlatform/cloud-tools-for-java FYI
@tswast, @jerjou FYI

**Review by tswast — COMMENTED** [review]
👍

**Comment by lesv** [comment]
Pushed to maven central as 0.3.0, should be published by Monday.

**Comment by jerjou** [comment]
Woohoo!

**Comment by elharo** [comment]
This may break CT4J's integration tests (which is _not_ a request for a rollback). However I do want to think about how we might decouple the integration tests from the specific latest version pushed to Maven Central.

**Comment by lesv** [comment]
0.3.0 is now present and available.

**Pull request merged**
