### PR TITLE
Update endpoints samples

### PR DESCRIPTION
**Pull request by frankyn**
* Updated -Dvariables to be more verbose.
* Updated plugin/dependency versions
* Removed iOS from samples
* Updated README to call out necessary information for discovery doc workflow.

### CODE REVIEW

**Comment by frankyn** [comment]
PTAL @lesv

**Comment by lesv** [comment]
I'm happy, but we will probably have an updated version next week.

**Comment by frankyn** [comment]
Yep, I asked before speaking with Patrick.
I'll wait till the updates are out.

**Comment by frankyn** [comment]
@lesv PTAL.

**Comment by lesv** [comment]
@frankyn  Unless it's urgent, I'll defer review to this weekend.

**Comment by frankyn** [comment]
@lesv I wanted to start working on updating the maven archetypes on Maven Central. It was mentioned to me that there may be a delay when deploying to Maven Central. 

As I haven't deployed an artifact yet, I'd like to get started.

**Comment by lesv** [comment]
k - I'm starting to review.

**Comment by lesv** [comment]
I've asked for changes verbally.

**Review by lesv — APPROVED** [review]

**Pull request merged**
